import = [
  "~/.config/alacritty/themes/nord.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "Liga SFMono Nerd Font"
size = 12
offset.y = 4 
glyph_offset.y = 2

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
