format = """
${custom.bw_session}\
$directory[\uE0B0](fg:bright-black bg:black)\
$git_branch$git_status[\uE0B0](fg:black bg:none)\
$character
"""
right_format = """
$cmd_duration\
$time
"""
add_newline = false

[character]
format = " "

[directory]
format = "[ $path ]($style)"
style = "bg:bright-black fg:white dimmed"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[custom.bw_session]
format = "[ •](bg:green fg:bright-black)[\uE0B0](fg:green bg:bright-black)"
when = 'test -n "$BW_SESSION"'

[git_branch]
format = "[ $branch ]($style)"
style = "bg:black fg:white dimmed"
always_show_remote = true

[git_status]
format = "([$all_status ]($style))"
style = "bg:black fg:bright-white bold"
ahead = "⇡"
behind = "⇣"
diverged = "⇕(red)"
up_to_date = ""
untracked = "[●](bg:black fg:yellow)"
stashed = "[●](bg:black fg:white)"
modified = "[●](bg:black fg:cyan)"
staged = "[●](bg:black fg:green)"
renamed = "[→ ](bg:black fg:cyan)"
deleted = "[●](bg:black fg:red)"

[time]
format = "[ $time ]($style)"
style = "bg:bright-black fg:white dimmed"
disabled = false
time_format = "%R"

[cmd_duration]
format = "[ $duration ]($style)"
style = "bg:black fg:white dimmed"
min_time = 0
